name: Print Python File
on: [push]

jobs:
  display-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Required to access your repository files
      
      - name: Print main.py contents
        run: |
          echo "📄 Contents of main.py:"
          cat main.py